services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: dev
    volumes:
      - ./:/app
    command: 'pnpm run dev'
    ports:
      - 3000:3000
  db:
    image: mysql:8
    ports:
      - 6033:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=envstockexchange
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
